# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
 
name: Python application
 
on:
  schedule:
    - cron: '0 0 * * *'
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f config.txt ]; then pip install -r config.txt; fi
    - name: SSR CheckOut
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python main.py
